-- ArcList schema — PostgreSQL version (converted from MySQL arclist.sql)
-- Run this once against your Render Postgres database.

-- Generic trigger to emulate MySQL's "ON UPDATE CURRENT_TIMESTAMP"
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================
-- users
-- =========================
CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name VARCHAR(100) NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(255) DEFAULT NULL,
  bio TEXT,
  favourite_hobby VARCHAR(100) DEFAULT NULL,
  theme_name VARCHAR(100) DEFAULT 'Summer Raspberry',
  install_prompt_dismissed BOOLEAN DEFAULT FALSE,
  install_prompt_installed BOOLEAN DEFAULT FALSE,
  login_count INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  theme VARCHAR(50) DEFAULT 'summer-raspberry',
  default_planning_mode VARCHAR(20) DEFAULT 'todo' CHECK (default_planning_mode IN ('todo','timetable')),
  default_task_duration INT DEFAULT 30,
  profile_photo_url VARCHAR(255) DEFAULT NULL,
  notification_enabled BOOLEAN DEFAULT TRUE,
  daily_review_reminder BOOLEAN DEFAULT TRUE,
  collaboration_notifications BOOLEAN DEFAULT TRUE,
  privacy_profile_visibility VARCHAR(20) DEFAULT 'friends' CHECK (privacy_profile_visibility IN ('private','friends','public')),
  allow_friend_requests BOOLEAN DEFAULT TRUE,
  allow_collaboration BOOLEAN DEFAULT TRUE,
  preferred_planning_mode VARCHAR(20) DEFAULT 'todo' CHECK (preferred_planning_mode IN ('todo','timetable')),
  notifications_enabled BOOLEAN DEFAULT TRUE,
  reminder_notifications BOOLEAN DEFAULT TRUE,
  daily_review_notifications BOOLEAN DEFAULT TRUE,
  profile_visibility VARCHAR(20) DEFAULT 'friends' CHECK (profile_visibility IN ('private','friends','public'))
);

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================
-- task_tags
-- =========================
CREATE TABLE task_tags (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(50) NOT NULL,
  color VARCHAR(20) NOT NULL DEFAULT '#720137',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_task_tags_user_id ON task_tags(user_id);

-- =========================
-- tasks
-- =========================
CREATE TABLE tasks (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(150) NOT NULL,
  description TEXT,
  priority VARCHAR(20) DEFAULT 'medium' CHECK (priority IN ('low','medium','high','urgent')),
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending','in_progress','completed','archived')),
  planning_mode VARCHAR(20) DEFAULT 'todo' CHECK (planning_mode IN ('todo','timetable')),
  difficulty_level SMALLINT DEFAULT 3,
  estimated_minutes INT DEFAULT NULL,
  due_date TIMESTAMP DEFAULT NULL,
  reminder_at TIMESTAMP DEFAULT NULL,
  is_recurring BOOLEAN DEFAULT FALSE,
  recurrence_pattern VARCHAR(50) DEFAULT NULL,
  tag_id INT DEFAULT NULL REFERENCES task_tags(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP DEFAULT NULL
);
CREATE INDEX idx_tasks_user_id ON tasks(user_id);
CREATE INDEX idx_tasks_tag_id ON tasks(tag_id);

CREATE TRIGGER trg_tasks_updated_at
BEFORE UPDATE ON tasks
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================
-- day_plans
-- =========================
CREATE TABLE day_plans (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  plan_date DATE NOT NULL,
  planning_mode VARCHAR(20) DEFAULT 'todo' CHECK (planning_mode IN ('todo','timetable')),
  notes TEXT,
  is_locked BOOLEAN DEFAULT FALSE,
  locked_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, plan_date)
);

CREATE TRIGGER trg_day_plans_updated_at
BEFORE UPDATE ON day_plans
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================
-- day_plan_tasks
-- =========================
CREATE TABLE day_plan_tasks (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_plan_id INT NOT NULL REFERENCES day_plans(id) ON DELETE CASCADE,
  task_id INT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  sort_order INT DEFAULT 0,
  planned_start TIMESTAMP DEFAULT NULL,
  planned_end TIMESTAMP DEFAULT NULL,
  added_after_lock BOOLEAN DEFAULT FALSE,
  completed_in_plan BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (day_plan_id, task_id)
);
CREATE INDEX idx_day_plan_tasks_task_id ON day_plan_tasks(task_id);

-- =========================
-- daily_evaluations
-- =========================
CREATE TABLE daily_evaluations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  plan_date DATE NOT NULL,
  completion_percentage DECIMAL(5,2) DEFAULT 0.00,
  completed_tasks_count INT DEFAULT 0,
  pending_tasks_count INT DEFAULT 0,
  overdue_tasks_count INT DEFAULT 0,
  strongest_category VARCHAR(100) DEFAULT NULL,
  most_skipped_category VARCHAR(100) DEFAULT NULL,
  total_estimated_minutes_completed INT DEFAULT 0,
  consistency_score DECIMAL(5,2) DEFAULT 0.00,
  summary_note TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, plan_date)
);

CREATE TRIGGER trg_daily_evaluations_updated_at
BEFORE UPDATE ON daily_evaluations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================
-- friend_requests
-- =========================
CREATE TABLE friend_requests (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  receiver_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected','cancelled')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (sender_id, receiver_id)
);
CREATE INDEX idx_friend_requests_receiver_id ON friend_requests(receiver_id);

CREATE TRIGGER trg_friend_requests_updated_at
BEFORE UPDATE ON friend_requests
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================
-- friends
-- =========================
CREATE TABLE friends (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  friend_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, friend_id)
);
CREATE INDEX idx_friends_friend_id ON friends(friend_id);

-- =========================
-- messages
-- =========================
CREATE TABLE messages (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  receiver_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_messages_sender_id ON messages(sender_id);
CREATE INDEX idx_messages_receiver_id ON messages(receiver_id);

-- =========================
-- notifications
-- =========================
CREATE TABLE notifications (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(30) DEFAULT 'system' CHECK (type IN ('task_reminder','overdue_alert','daily_review','collaboration','system')),
  title VARCHAR(150) NOT NULL,
  message TEXT NOT NULL,
  related_task_id INT DEFAULT NULL REFERENCES tasks(id) ON DELETE SET NULL,
  scheduled_for TIMESTAMP DEFAULT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  is_sent BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  related_request_id INT DEFAULT NULL REFERENCES friend_requests(id) ON DELETE SET NULL
);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_related_task_id ON notifications(related_task_id);
CREATE INDEX idx_notifications_related_request_id ON notifications(related_request_id);

CREATE TRIGGER trg_notifications_updated_at
BEFORE UPDATE ON notifications
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
